### Numpy array operation

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing", arr[2:7]) # slicing
print("slicing with step", arr[2:7:2]) # slicing
print("Negative indexing", arr[::-1]) # slicing, reversing technique


basic slicing [3 4 5 6 7]
slicing with step [3 5 7]
Negative indexing [10  9  8  7  6  5  4  3  2  1]


In [4]:
arr_2d = np.array([[1,2,3],
                   [3,4,5,],
                   [7,8,9]])
print("specific element", arr_2d[1,2])
print("entire row", arr_2d[1])
print("entire col", arr_2d[:,1])

specific element 5
entire row [3 4 5]
entire col [2 4 8]


Sorting


In [5]:
unsorted = np.array([3,5,4,2,3,1,8,9,6,10,7,2])
print("sorted array \n", np.sort(unsorted))

arr_2d = np.array([[3,1],[6,2],[2,1]])
print("sorted 2D array \n", np.sort(arr_2d, axis = 1)) # 0 : for column based sorting 
# 1: for row wise sorting

sorted array 
 [ 1  2  2  3  3  4  5  6  7  8  9 10]
sorted 2D array 
 [[1 3]
 [2 6]
 [1 2]]


Filtering

In [6]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_numb = number[number%2==0]
print("even numbers :\n",even_numb)

even numbers :
 [ 2  4  6  8 10]


Filtering with Mask

In [7]:
mask = number>5
print("number greator than", number[mask])

number greator than [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [8]:
indices = [0,2,4]
print(number[indices])

[1 3 5]


In [9]:
where_result = np.where(number>5)
print(where_result)
print("np where", number[where_result])

(array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


### Adding and removing data

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 3 4 5]


Array compatibiity

In [12]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([1,2,3])

print("comapatibility shapes", a.shape == b.shape)

comapatibility shapes True


In [13]:
original  = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("with new col",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 7]
 [3 4 8]]


In [15]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr,2)
print("array after deletion \n" ,deleted)

array after deletion 
 [1 2 4 5 6]
