## Numpy array and basics

In [5]:
import numpy as np

### creating array form list 

In [10]:
arr_1d = np.array([1,2,3,4,5])
print("1d array: ", arr_1d)

1d array:  [1 2 3 4 5]


### list vs numpy array

In [19]:
py_list = [1,2,3,4]
print("python list multiplication", py_list*2)

np_array =  np.array([1,2,3,4])
print("python array multiplication :", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000)]
print("\n list opertaion time :", time.time()-start)

start = time.time()
np_array = np.arange(1000)*2
print("\n array opertaion time :", time.time()-start)


python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python array multiplication : [2 4 6 8]

 list opertaion time : 0.0

 array opertaion time : 0.0


### creating array from scratch

In [26]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((3,4))
print("ones array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random value array: \n",random)

sequence = np.arange(0,10,2)
print("sequence value array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random value array: 
 [[0.88832039 0.75747908 0.2384569 ]
 [0.42022265 0.89360392 0.32527142]]
sequence value array: 
 [0 2 4 6 8]


#### Vector , matrix, Tensor

In [30]:
vector = np.array([1,2,3])
print("array : \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix : \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor : \n", tensor)


array : 
 [1 2 3]
matrix : 
 [[1 2 3]
 [4 5 6]]
tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties 

In [35]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("DType",arr.dtype)

shape (2, 3)
dimension 2
size 6
DType int64


Array reshaping

In [45]:
arr = np.arange(12)
print("Original array \n ",arr)

reshape = arr.reshape((3,4))
print("reshaped array \n",reshape)

flatten = reshape.flatten()
print("flattened array \n", flatten)

# Ravel : return view instead of copy
ravel = reshape.ravel()
print("ravel array \n", ravel)

# Transpose 
transpose = reshape.T
print("Transpose array \n", transpose)


Original array 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
